#!/usr/bin/env bash

command="$1"
if [ -z $command ]; then

  cat <<USAGE
rb ($RB_RELEASE release)

usage: rb [@<version>]
       rb -f <version_file>
       rb help [<cmd>]
       rb status
       rb init [--auto]
       rb --version

More Info:
  https://github.com/redding/rb/blob/$RB_RELEASE/README.md
USAGE
  exit 0

else

  if [[ "$command" == "help" ]]; then

    cat <<USAGE
Print command usage info.

usage: rb help
       rb help [cmd]
USAGE
    exit 0

  elif [[ "$command" == "status" ]]; then

    cat <<USAGE
Print the current version and source info

usage: rb status
USAGE
    exit 0

  elif [[ "$command" == "init" ]]; then

    cat <<USAGE
Output a script to eval in the shell.

usage: eval "\$(rb init)"
       eval "\$(rb init --auto)"
USAGE
    exit 0

  else
    echo "rb: no such command \`$command'" >&2
    exit 1
  fi

fi

