#!/usr/bin/env bash

cat <<BASH_TAB_COMPLETION
if command -v complete >/dev/null 2>&1; then
  _rb_complete_version() {
    if [ -d "$RB_RUBIES_DIR" ]; then
      cur="\${COMP_WORDS[COMP_CWORD]}"
      versions=\$(\\ls -1 $RB_RUBIES_DIR | sed -e "s/^/@/")
      cmds=\$(\\ls -1 `which rb`/.. | grep rb-  | sed -e "s/^rb-//" | sed -e "s/*$//")

      if [[ \$COMP_CWORD == 1 ]]; then
        COMPREPLY=( \$(compgen -W "\${cmds} \${versions} @system --version -f" -- \${cur}) )
        return 0
      fi

      if [[ \$COMP_CWORD == 2 ]] && [[ \${COMP_WORDS[1]} == 'exec' ]]; then
        COMPREPLY=( \$(compgen -W "\${versions} @system -f" -- \${cur}) )
        return 0
      fi

      if [[ \$COMP_CWORD == 2 ]] && [[ \${COMP_WORDS[1]} == 'init' ]]; then
        COMPREPLY=( \$(compgen -W "--auto" -- \${cur}) )
        return 0
      fi

      if [[ \$COMP_CWORD == 2 ]] && [[ \${COMP_WORDS[1]} == 'help' ]]; then
        COMPREPLY=( \$(compgen -W "\${cmds}" -- \${cur}) )
        return 0
      fi
    fi
  }
  complete -o default -F _rb_complete_version rb
fi
BASH_TAB_COMPLETION

if [ "$1" = "--auto" ]; then

  # (optional) auto mode (update ruby version as you change directories)

  cat <<AUTO_MODE
PROMPT_COMMAND="${PROMPT_COMMAND%% }"
if [[ -n "$PROMPT_COMMAND" ]]; then
  if [[ ! "$PROMPT_COMMAND" == *_rb_auto_activate* ]]; then
    PROMPT_COMMAND="${PROMPT_COMMAND%%;}"
    PROMPT_COMMAND="$PROMPT_COMMAND; _rb_auto_activate"
  fi
else
  PROMPT_COMMAND="_rb_auto_activate"
fi
AUTO_MODE

fi

cat <<SOURCE_RB
source `which rb`
SOURCE_RB
